services:
    openra.openrauseraccounts.controller:
        class: openra\openrauseraccounts\controller\main
        arguments:
            - '@openra.openrauseraccounts.core'
            - '@dbal.conn'
            - '@config'
            - '@request'
            - '@passwords.manager'
            - '%core.table_prefix%'
    openra.openrauseraccounts.core:
        class: openra\openrauseraccounts\core\core
        arguments:
            - '@dbal.conn'
